<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><SptRoot Condition="'$(SptRoot)' == ''">C:/SPT</SptRoot></PropertyGroup><ItemGroup><Reference Include="Unity.VectorGraphics"><HintPath>$(SptRoot)/EscapeFromTarkov_Data/Managed/Unity.VectorGraphics.dll</HintPath></Reference><Reference Include="UnityEngine"><HintPath>$(SptRoot)/EscapeFromTarkov_Data/Managed/UnityEngine.dll</HintPath></Reference><Reference Include="UnityEngine.CoreModule"><HintPath>$(SptRoot)/EscapeFromTarkov_Data/Managed/UnityEngine.CoreModule.dll</HintPath></Reference></ItemGroup></Project>